[package]
name = "flowcom"
version = "0.1.0"
edition = "2021"
authors = ["Jared Moulton <jaredmoulton3@gmail.com>"]
license = "MIT"
description = """
flowcom is a collection of UI components for floem
"""
homepage = "https://github.com/jrmoulton/flowcom"
repository = "https://github.com/jrmoulton/flowcom"


[dependencies]
# crossbeam-channel = "0.5.11"
floem = { git = "https://github.com/lapce/floem", features = ["futures"], default-features = false }
# floem = { path = "../floem", default-features = false, features = ["futures"]}
# im = "15.1.0"
# nucleo = {git = "https://github.com/helix-editor/nucleo"}
lucide-floem = { git = "https://github.com/jrmoulton/lucide-floem", features = [
    "use-lapce",
] }
# lucide-floem = { path = "../lucide-floem" }
jiff = "0.1.4"

# helix-view = {path = "../helix/helix-view", default-features = false}
# helix-loader = {path = "../helix/helix-loader"}
# helix-core = {path = "../helix/helix-core"}
# arc-swap = "1.7.1"
# tokio = {version = "1.39.2"}
# tokio-stream = "0.1.15"
# paste = "1.0.15"

# [dev-dependencies]
# tokio
